language: python
python:
  - "2.7"
  # - "3.4"
  # - "3.5"

before_script:
  - sudo apt-get install swig cython

# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests

script: make test-other-wrapping-cpp
